development:
  adapter: sqlite3
  database: rentalbike_development
  pool: 5
  timeout: 5000
test:
  adapter: sqlite3
  database: rentalbike_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: rentalbike_production
  pool: 5
  timeout: 5000
